# command line: main.py finetune_evaluation --config config/SHREC/joint/joint.yaml --phase train --device 0

base_lr: 0.05
batch_size: 32
config: config/SHREC/joint/joint.yaml
debug: false
device:
- 0
eval_interval: 5
grad_clip_norm: 1.0
ignore_weights: []
lambda_entropy: 0.001
lambda_kd: 0.3
lambda_ortho: 0.1
log_interval: 100
loss: torch.nn.CrossEntropyLoss
loss_args: {}
lr_decay_rate: 0.1
model: net.dsa_hgn.Model
model_args:
    adaptive: true
    base_channels: 64
    drop_out: 0.0
    graph: graph.shrec.Graph
    graph_args:
        labeling_mode: spatial
    in_channels: 3
    num_class: 14
    num_hyperedges: 16
    num_person: 1
    num_point: 22
    num_stages: 10
    use_virtual_conn: true
nesterov: true
num_epoch: 150
num_worker: 4
optimizer: SGD
optimizer_args: {}
pavi_log: false
phase: train
print_log: true
save_interval: 5
save_log: true
save_result: true
show_topk:
- 1
- 5
start_epoch: 0
step:
- 70
- 100
stream: joint
teacher_weights: null
test_batch_size: 32
test_feeder: feeder.feeder_egogesture.Feeder
test_feeder_args:
    bone: false
    data_path: /Users/gzp/Desktop/exp/DATA/SHREC2017_data/val_data.npy
    debug: false
    label_path: /Users/gzp/Desktop/exp/DATA/SHREC2017_data/val_label.pkl
    normalization: true
    split: test
    use_mmap: true
    vel: false
    window_size: 180
train_feeder: feeder.feeder_egogesture.Feeder
train_feeder_args:
    bone: false
    data_path: /Users/gzp/Desktop/exp/DATA/SHREC2017_data/train_data.npy
    debug: false
    label_path: /Users/gzp/Desktop/exp/DATA/SHREC2017_data/train_label.pkl
    normalization: true
    random_choose: true
    random_move: true
    random_rot: true
    random_shift: true
    repeat: 5
    shear_amplitude: 0.5
    split: train
    temperal_padding_ratio: 6
    use_mmap: true
    vel: false
    window_size: 180
use_gpu: true
warm_up_epoch: 5
weight_decay: 0.0005
weights: null
work_dir: ./work_dir/SHREC/joint_v2
